"""Data-Gateway error hierarchy."""

from enum import Enum

from empire_core.errors import EmpireError


class GatewayError(EmpireError):
    """Base exception for all Data-Gateway errors."""


class ErrorCode(str, Enum):
    # Provider
    PROVIDER_AUTH_FAILED = "PROVIDER_AUTH_FAILED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_SCHEMA_DRIFT = "PROVIDER_SCHEMA_DRIFT"

    # Cache
    CACHE_READ_FAILED = "CACHE_READ_FAILED"
    CACHE_WRITE_FAILED = "CACHE_WRITE_FAILED"
    CACHE_CONNECTION_FAILED = "CACHE_CONNECTION_FAILED"

    # WebSocket
    WS_AUTH_FAILED = "WS_AUTH_FAILED"
    WS_SUBSCRIBE_FAILED = "WS_SUBSCRIBE_FAILED"
    WS_CONNECTION_LOST = "WS_CONNECTION_LOST"

    # Normalization
    NORMALIZATION_FAILED = "NORMALIZATION_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # Redis Streams
    STREAM_PUBLISH_FAILED = "STREAM_PUBLISH_FAILED"
    STREAM_CONNECTION_FAILED = "STREAM_CONNECTION_FAILED"
