"""Pydantic schemas for messages and data.

This module re-exports all models from empire_schemas (the canonical source)
and adds gateway-specific models not present in the shared package.
"""

# ── Re-export everything from empire_schemas ──
from empire_schemas import (
    FEED_UNIQUE_FIELDS,
    INSTRUMENT_KEY_PATTERNS,
    SCHEMA_VERSION,
    Account,
    AccountConfigResponse,
    AccountConfigurations,
    AccountResponse,
    ActivitiesResponse,
    Activity,
    Asset,
    AssetResponse,
    AssetsResponse,
    AuctionsResponse,
    AuthMessage,
    AuthResult,
    Calendar,
    CalendarResponse,
    Clock,
    ClockResponse,
    ConditionCodesResponse,
    CorporateActionsResponse,
    CryptoBarsResponse,
    CryptoLatestBarsResponse,
    CryptoLatestTradesResponse,
    CryptoOrderbookResponse,
    CryptoQuoteResponse,
    CryptoSnapshotResponse,
    CryptoTradesResponse,
    ErrorResponse,
    EventEnvelope,
    ExchangeCodesResponse,
    FixedIncomeResponse,
    ForexHistoricalResponse,
    ForexRatesResponse,
    HealthResponse,
    HistoricalQuotesResponse,
    LatestBarsResponse,
    LatestTradesResponse,
    MostActivesResponse,
    MoversData,
    MoversResponse,
    NewsResponse,
    NormalizedBar,
    NormalizedCorporateAction,
    NormalizedDarkpoolTrade,
    NormalizedEarnings,
    NormalizedETFFlow,
    NormalizedETFHolding,
    NormalizedFlowAlert,
    NormalizedForexRate,
    NormalizedFTD,
    NormalizedFundamentals,
    NormalizedGreekExposure,
    NormalizedHottestChain,
    NormalizedInsiderTrade,
    NormalizedInstitutionHolding,
    NormalizedIVRank,
    NormalizedIVTermStructure,
    NormalizedMarketTide,
    NormalizedMaxPain,
    NormalizedMostActive,
    NormalizedMover,
    NormalizedNetPremiumTick,
    NormalizedNewsArticle,
    NormalizedOIChange,
    NormalizedOptionContract,
    NormalizedOrderbook,
    NormalizedOrderbookLevel,
    NormalizedPoliticianTrade,
    NormalizedQuote,
    NormalizedScreenerResult,
    NormalizedSeasonality,
    NormalizedSectorTide,
    NormalizedShortData,
    NormalizedTrade,
    NormalizedVolatilityStats,
    OptionBarsResponse,
    OptionChainResponse,
    OptionLatestTradesResponse,
    OptionQuoteResponse,
    OptionSnapshotResponse,
    OptionSnapshotsResponse,
    OptionTradesResponse,
    Order,
    OrderResponse,
    OrdersListResponse,
    PortfolioHistory,
    PortfolioHistoryResponse,
    Position,
    PositionResponse,
    PositionsListResponse,
    ResponseMeta,
    SnapshotsResponse,
    StockBarsResponse,
    StockQuoteResponse,
    StockSnapshot,
    StockSnapshotResponse,
    StockTradesResponse,
    SubscribeMessage,
    SubscriptionAck,
    SuccessResponse,
    UnsubscribeMessage,
    Watchlist,
    WatchlistResponse,
    WatchlistsListResponse,
    compute_event_id,
    extract_unique_fields,
    infer_instrument_type,
    make_instrument_key,
    validate_instrument_key,
)

# Auction is in empire_schemas.responses but also re-exported here for convenience
from empire_schemas.responses import Auction

# ── Gateway-specific re-exports from submodules ──
from gateway.schemas.fundamentals import NormalizedBorrowCost
from gateway.schemas.news import NormalizedNewsImage
from gateway.schemas.options import NormalizedOptionTrade

__all__ = [
    "SCHEMA_VERSION",
    # Market data
    "NormalizedBar",
    "NormalizedQuote",
    "NormalizedTrade",
    "NormalizedForexRate",
    # Options
    "NormalizedFlowAlert",
    "NormalizedOptionContract",
    "NormalizedGreekExposure",
    "NormalizedHottestChain",
    # Alternative
    "NormalizedDarkpoolTrade",
    "NormalizedInsiderTrade",
    "NormalizedInstitutionHolding",
    "NormalizedPoliticianTrade",
    # Fundamentals
    "NormalizedFundamentals",
    "NormalizedEarnings",
    "NormalizedCorporateAction",
    # Analytics
    "NormalizedNetPremiumTick",
    "NormalizedMaxPain",
    "NormalizedIVRank",
    "NormalizedOIChange",
    "NormalizedETFHolding",
    "NormalizedETFFlow",
    "NormalizedShortData",
    "NormalizedFTD",
    "NormalizedMarketTide",
    "NormalizedSectorTide",
    "NormalizedIVTermStructure",
    "NormalizedVolatilityStats",
    "NormalizedSeasonality",
    "NormalizedOrderbookLevel",
    "NormalizedOrderbook",
    "NormalizedMostActive",
    "NormalizedMover",
    # Envelope
    "EventEnvelope",
    "make_instrument_key",
    "compute_event_id",
    "extract_unique_fields",
    "infer_instrument_type",
    "FEED_UNIQUE_FIELDS",
    # Instrument
    "validate_instrument_key",
    "INSTRUMENT_KEY_PATTERNS",
    # Responses
    "AuthMessage",
    "SubscribeMessage",
    "UnsubscribeMessage",
    "AuthResult",
    "SubscriptionAck",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    "ResponseMeta",
    "StockSnapshot",
    "Auction",
    "NormalizedNewsArticle",
    "NormalizedScreenerResult",
    "StockBarsResponse",
    "StockQuoteResponse",
    "StockTradesResponse",
    "StockSnapshotResponse",
    "LatestBarsResponse",
    "LatestTradesResponse",
    "HistoricalQuotesResponse",
    "SnapshotsResponse",
    "AuctionsResponse",
    "OptionChainResponse",
    "OptionSnapshotResponse",
    "OptionBarsResponse",
    "OptionQuoteResponse",
    "OptionTradesResponse",
    "OptionLatestTradesResponse",
    "OptionSnapshotsResponse",
    "CryptoBarsResponse",
    "CryptoTradesResponse",
    "CryptoQuoteResponse",
    "CryptoSnapshotResponse",
    "CryptoLatestBarsResponse",
    "CryptoLatestTradesResponse",
    "CryptoOrderbookResponse",
    "ForexRatesResponse",
    "ForexHistoricalResponse",
    "NewsResponse",
    "MostActivesResponse",
    "MoversData",
    "MoversResponse",
    "CorporateActionsResponse",
    "ConditionCodesResponse",
    "ExchangeCodesResponse",
    "FixedIncomeResponse",
    # Trading
    "Account",
    "Order",
    "Position",
    "PortfolioHistory",
    "Watchlist",
    "Clock",
    "Calendar",
    "Asset",
    "AccountConfigurations",
    "Activity",
    "AccountResponse",
    "OrderResponse",
    "OrdersListResponse",
    "PositionResponse",
    "PositionsListResponse",
    "PortfolioHistoryResponse",
    "WatchlistResponse",
    "WatchlistsListResponse",
    "ClockResponse",
    "CalendarResponse",
    "AccountConfigResponse",
    "ActivitiesResponse",
    "AssetsResponse",
    "AssetResponse",
    # Gateway-specific
    "NormalizedOptionTrade",
    "NormalizedBorrowCost",
    "NormalizedNewsImage",
]
