"""Pydantic schemas for messages and data.

This module re-exports all models from empire_schemas (the canonical
source) and adds gateway-specific models not present in the shared
package.

A small set of core models are intentionally shadowed by **gateway-strict
subclasses** defined in `gateway.schemas._strict`. The strict subclasses
inherit from the canonical empire-schemas models so `isinstance` still
works, but add Data-Gateway-side invariants:

  * datetime fields must be timezone-aware (UTC required)
  * prices/strikes must be > 0
  * volume/OI/sizes must be >= 0
  * `ResponseMeta.provider` is required (no silent `"alpaca"` default)

Cleanup of these invariants in `empire-schemas` itself is tracked as a
follow-up task; until that lands, the gateway is the source of truth.
"""

# ── Re-export the empire_schemas models we do NOT shadow ──
from empire_schemas import (
    Account,
    AccountConfigResponse,
    AccountConfigurations,
    AccountResponse,
    ActivitiesResponse,
    Activity,
    Asset,
    AssetResponse,
    AssetsResponse,
    AuctionsResponse,
    AuthMessage,
    AuthResult,
    Calendar,
    CalendarResponse,
    Clock,
    ClockResponse,
    ConditionCodesResponse,
    CorporateActionsResponse,
    CryptoBarsResponse,
    CryptoLatestBarsResponse,
    CryptoLatestTradesResponse,
    CryptoOrderbookResponse,
    CryptoQuoteResponse,
    CryptoSnapshotResponse,
    CryptoTradesResponse,
    ErrorResponse,
    ExchangeCodesResponse,
    FixedIncomeResponse,
    ForexHistoricalResponse,
    ForexRatesResponse,
    HealthResponse,
    HistoricalQuotesResponse,
    LatestBarsResponse,
    LatestTradesResponse,
    MostActivesResponse,
    MoversData,
    MoversResponse,
    NewsResponse,
    NormalizedCorporateAction,
    NormalizedEarnings,
    NormalizedETFFlow,
    NormalizedETFHolding,
    NormalizedFTD,
    NormalizedFundamentals,
    NormalizedHottestChain,
    NormalizedInstitutionHolding,
    NormalizedIVRank,
    NormalizedIVTermStructure,
    NormalizedMaxPain,
    NormalizedMostActive,
    NormalizedMover,
    NormalizedOIChange,
    NormalizedOrderbook,
    NormalizedOrderbookLevel,
    NormalizedScreenerResult,
    NormalizedSeasonality,
    NormalizedShortData,
    NormalizedVolatilityStats,
    OptionBarsResponse,
    OptionChainResponse,
    OptionLatestTradesResponse,
    OptionQuoteResponse,
    OptionSnapshotResponse,
    OptionSnapshotsResponse,
    OptionTradesResponse,
    Order,
    OrderResponse,
    OrdersListResponse,
    PortfolioHistory,
    PortfolioHistoryResponse,
    Position,
    PositionResponse,
    PositionsListResponse,
    SnapshotsResponse,
    StockBarsResponse,
    StockQuoteResponse,
    StockSnapshot,
    StockSnapshotResponse,
    StockTradesResponse,
    SubscribeMessage,
    SubscriptionAck,
    SuccessResponse,
    UnsubscribeMessage,
    Watchlist,
    WatchlistResponse,
    WatchlistsListResponse,
)

# Auction is in empire_schemas.responses but also re-exported here for convenience
from empire_schemas.responses import Auction

# ── Gateway-strict subclasses (shadow the empire_schemas defaults) ──
# Imported AFTER the wholesale empire_schemas import above so they win
# the namespace.
from gateway.schemas._strict import (  # noqa: E402
    NormalizedBar,
    NormalizedDarkpoolTrade,
    NormalizedFlowAlert,
    NormalizedForexRate,
    NormalizedGreekExposure,
    NormalizedInsiderTrade,
    NormalizedMarketTide,
    NormalizedNetPremiumTick,
    NormalizedNewsArticle,
    NormalizedOptionContract,
    NormalizedPoliticianTrade,
    NormalizedQuote,
    NormalizedSectorTide,
    NormalizedTrade,
    ResponseMeta,
)

# ── Gateway-specific re-exports from submodules ──
from gateway.schemas.fundamentals import NormalizedBorrowCost  # noqa: E402
from gateway.schemas.news import NormalizedNewsImage  # noqa: E402
from gateway.schemas.options import NormalizedOptionTrade  # noqa: E402

__all__ = [
    "SCHEMA_VERSION",
    # Market data
    "NormalizedBar",
    "NormalizedQuote",
    "NormalizedTrade",
    "NormalizedForexRate",
    # Options
    "NormalizedFlowAlert",
    "NormalizedOptionContract",
    "NormalizedGreekExposure",
    "NormalizedHottestChain",
    # Alternative
    "NormalizedDarkpoolTrade",
    "NormalizedInsiderTrade",
    "NormalizedInstitutionHolding",
    "NormalizedPoliticianTrade",
    # Fundamentals
    "NormalizedFundamentals",
    "NormalizedEarnings",
    "NormalizedCorporateAction",
    # Analytics
    "NormalizedNetPremiumTick",
    "NormalizedMaxPain",
    "NormalizedIVRank",
    "NormalizedOIChange",
    "NormalizedETFHolding",
    "NormalizedETFFlow",
    "NormalizedShortData",
    "NormalizedFTD",
    "NormalizedMarketTide",
    "NormalizedSectorTide",
    "NormalizedIVTermStructure",
    "NormalizedVolatilityStats",
    "NormalizedSeasonality",
    "NormalizedOrderbookLevel",
    "NormalizedOrderbook",
    "NormalizedMostActive",
    "NormalizedMover",
    # Responses
    "AuthMessage",
    "SubscribeMessage",
    "UnsubscribeMessage",
    "AuthResult",
    "SubscriptionAck",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    "ResponseMeta",
    "StockSnapshot",
    "Auction",
    "NormalizedNewsArticle",
    "NormalizedScreenerResult",
    "StockBarsResponse",
    "StockQuoteResponse",
    "StockTradesResponse",
    "StockSnapshotResponse",
    "LatestBarsResponse",
    "LatestTradesResponse",
    "HistoricalQuotesResponse",
    "SnapshotsResponse",
    "AuctionsResponse",
    "OptionChainResponse",
    "OptionSnapshotResponse",
    "OptionBarsResponse",
    "OptionQuoteResponse",
    "OptionTradesResponse",
    "OptionLatestTradesResponse",
    "OptionSnapshotsResponse",
    "CryptoBarsResponse",
    "CryptoTradesResponse",
    "CryptoQuoteResponse",
    "CryptoSnapshotResponse",
    "CryptoLatestBarsResponse",
    "CryptoLatestTradesResponse",
    "CryptoOrderbookResponse",
    "ForexRatesResponse",
    "ForexHistoricalResponse",
    "NewsResponse",
    "MostActivesResponse",
    "MoversData",
    "MoversResponse",
    "CorporateActionsResponse",
    "ConditionCodesResponse",
    "ExchangeCodesResponse",
    "FixedIncomeResponse",
    # Trading
    "Account",
    "Order",
    "Position",
    "PortfolioHistory",
    "Watchlist",
    "Clock",
    "Calendar",
    "Asset",
    "AccountConfigurations",
    "Activity",
    "AccountResponse",
    "OrderResponse",
    "OrdersListResponse",
    "PositionResponse",
    "PositionsListResponse",
    "PortfolioHistoryResponse",
    "WatchlistResponse",
    "WatchlistsListResponse",
    "ClockResponse",
    "CalendarResponse",
    "AccountConfigResponse",
    "ActivitiesResponse",
    "AssetsResponse",
    "AssetResponse",
    # Gateway-specific
    "NormalizedOptionTrade",
    "NormalizedBorrowCost",
    "NormalizedNewsImage",
]
