"""Empire Schemas — shared data contracts for all Empire services.

Import any model directly:
    from empire_schemas import NormalizedBar, EventEnvelope, Account
"""

from empire_schemas._version import SCHEMA_VERSION
from empire_schemas.alternative import (
    NormalizedDarkpoolTrade,
    NormalizedInsiderTrade,
    NormalizedInstitutionHolding,
    NormalizedPoliticianTrade,
)
from empire_schemas.analytics import (
    NormalizedETFFlow,
    NormalizedETFHolding,
    NormalizedFTD,
    NormalizedIVRank,
    NormalizedIVTermStructure,
    NormalizedMarketTide,
    NormalizedMaxPain,
    NormalizedMostActive,
    NormalizedMover,
    NormalizedNetPremiumTick,
    NormalizedOIChange,
    NormalizedOrderbook,
    NormalizedOrderbookLevel,
    NormalizedSeasonality,
    NormalizedSectorTide,
    NormalizedShortData,
    NormalizedVolatilityStats,
)
from empire_schemas.envelope import (
    FEED_UNIQUE_FIELDS,
    EventEnvelope,
    compute_event_id,
    extract_unique_fields,
    infer_instrument_type,
    make_instrument_key,
)
from empire_schemas.fundamentals import (
    NormalizedCorporateAction,
    NormalizedEarnings,
    NormalizedFundamentals,
)
from empire_schemas.instrument import (
    INSTRUMENT_KEY_PATTERNS,
    validate_instrument_key,
)
from empire_schemas.market_data import (
    NormalizedBar,
    NormalizedForexRate,
    NormalizedQuote,
    NormalizedTrade,
)
from empire_schemas.options import (
    NormalizedFlowAlert,
    NormalizedGreekExposure,
    NormalizedHottestChain,
    NormalizedOptionContract,
)
from empire_schemas.responses import (
    AuctionsResponse,
    AuthMessage,
    AuthResult,
    ConditionCodesResponse,
    CorporateActionsResponse,
    CryptoBarsResponse,
    CryptoLatestBarsResponse,
    CryptoLatestTradesResponse,
    CryptoOrderbookResponse,
    CryptoQuoteResponse,
    CryptoSnapshotResponse,
    CryptoTradesResponse,
    ErrorResponse,
    ExchangeCodesResponse,
    FixedIncomeResponse,
    ForexHistoricalResponse,
    ForexRatesResponse,
    HealthResponse,
    HistoricalQuotesResponse,
    LatestBarsResponse,
    LatestTradesResponse,
    MostActivesResponse,
    MoversData,
    MoversResponse,
    NewsResponse,
    NormalizedNewsArticle,
    NormalizedScreenerResult,
    OptionBarsResponse,
    OptionChainResponse,
    OptionLatestTradesResponse,
    OptionQuoteResponse,
    OptionSnapshotResponse,
    OptionSnapshotsResponse,
    OptionTradesResponse,
    ResponseMeta,
    SnapshotsResponse,
    StockBarsResponse,
    StockQuoteResponse,
    StockSnapshot,
    StockSnapshotResponse,
    StockTradesResponse,
    SubscribeMessage,
    SubscriptionAck,
    SuccessResponse,
    UnsubscribeMessage,
)
from empire_schemas.trading import (
    Account,
    AccountConfigResponse,
    AccountConfigurations,
    AccountResponse,
    ActivitiesResponse,
    Activity,
    Asset,
    AssetResponse,
    AssetsResponse,
    Calendar,
    CalendarResponse,
    Clock,
    ClockResponse,
    Order,
    OrderResponse,
    OrdersListResponse,
    PortfolioHistory,
    PortfolioHistoryResponse,
    Position,
    PositionResponse,
    PositionsListResponse,
    Watchlist,
    WatchlistResponse,
    WatchlistsListResponse,
)

__all__ = [
    "SCHEMA_VERSION",
    # Market data
    "NormalizedBar",
    "NormalizedQuote",
    "NormalizedTrade",
    "NormalizedForexRate",
    # Options
    "NormalizedFlowAlert",
    "NormalizedOptionContract",
    "NormalizedGreekExposure",
    "NormalizedHottestChain",
    # Alternative
    "NormalizedDarkpoolTrade",
    "NormalizedInsiderTrade",
    "NormalizedInstitutionHolding",
    "NormalizedPoliticianTrade",
    # Fundamentals
    "NormalizedFundamentals",
    "NormalizedEarnings",
    "NormalizedCorporateAction",
    # Analytics
    "NormalizedNetPremiumTick",
    "NormalizedMaxPain",
    "NormalizedIVRank",
    "NormalizedOIChange",
    "NormalizedETFHolding",
    "NormalizedETFFlow",
    "NormalizedShortData",
    "NormalizedFTD",
    "NormalizedMarketTide",
    "NormalizedSectorTide",
    "NormalizedIVTermStructure",
    "NormalizedVolatilityStats",
    "NormalizedSeasonality",
    "NormalizedOrderbookLevel",
    "NormalizedOrderbook",
    "NormalizedMostActive",
    "NormalizedMover",
    # Envelope
    "EventEnvelope",
    "make_instrument_key",
    "compute_event_id",
    "extract_unique_fields",
    "infer_instrument_type",
    "FEED_UNIQUE_FIELDS",
    # Instrument
    "validate_instrument_key",
    "INSTRUMENT_KEY_PATTERNS",
    # Responses
    "AuthMessage",
    "SubscribeMessage",
    "UnsubscribeMessage",
    "AuthResult",
    "SubscriptionAck",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    "ResponseMeta",
    "StockSnapshot",
    "NormalizedNewsArticle",
    "NormalizedScreenerResult",
    "StockBarsResponse",
    "StockQuoteResponse",
    "StockTradesResponse",
    "StockSnapshotResponse",
    "LatestBarsResponse",
    "LatestTradesResponse",
    "HistoricalQuotesResponse",
    "SnapshotsResponse",
    "AuctionsResponse",
    "OptionChainResponse",
    "OptionSnapshotResponse",
    "OptionBarsResponse",
    "OptionQuoteResponse",
    "OptionTradesResponse",
    "OptionLatestTradesResponse",
    "OptionSnapshotsResponse",
    "CryptoBarsResponse",
    "CryptoTradesResponse",
    "CryptoQuoteResponse",
    "CryptoSnapshotResponse",
    "CryptoLatestBarsResponse",
    "CryptoLatestTradesResponse",
    "CryptoOrderbookResponse",
    "ForexRatesResponse",
    "ForexHistoricalResponse",
    "NewsResponse",
    "MostActivesResponse",
    "MoversData",
    "MoversResponse",
    "CorporateActionsResponse",
    "ConditionCodesResponse",
    "ExchangeCodesResponse",
    "FixedIncomeResponse",
    # Trading
    "Account",
    "Order",
    "Position",
    "PortfolioHistory",
    "Watchlist",
    "Clock",
    "Calendar",
    "Asset",
    "AccountConfigurations",
    "Activity",
    "AccountResponse",
    "OrderResponse",
    "OrdersListResponse",
    "PositionResponse",
    "PositionsListResponse",
    "PortfolioHistoryResponse",
    "WatchlistResponse",
    "WatchlistsListResponse",
    "ClockResponse",
    "CalendarResponse",
    "AccountConfigResponse",
    "ActivitiesResponse",
    "AssetsResponse",
    "AssetResponse",
]
